apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinservice-mongo-prod
spec:
  selector:
    matchLabels:
      run: coinservice-mongo-prod
  replicas: 1
  template:
    metadata:
      labels:
        run: coinservice-mongo-prod
    spec:
      containers:
        - name: coinservice-mongo-prod-container
          image: mongo:4-bionic
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-volume
            - mountPath: /data/configdb
              name: mongodb-config-volume
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "example"

        - name: coinservice-mongo-express-prod-container
          image: mongo-express
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_SITE_BASEURL
              value: "/mongo-express/"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "localhost"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "example"
      volumes:
        - name: mongodb-data-volume
          hostPath:
            path: /home/coin-service/storage/prod/mongodb/mongodb-data-volume
            type: DirectoryOrCreate
        - name: mongodb-config-volume
          hostPath:
            path: /home/coin-service/storage/prod/mongodb/mongodb-config-volume
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: coinservice-mongo-prod
  labels:
    run: coinservice-mongo-prod
spec:
  type: ClusterIP
  clusterIP: 10.152.183.152
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: mongo-express
  selector:
    run: coinservice-mongo-prod